import Dog from 'assets/dog.svg'
import Horse from 'assets/horse.svg'
import Cow from 'assets/cow.svg'
// import Goat from 'assets/goat.svg'
import Cat from 'assets/cat.svg'
import Pig from 'assets/pig.svg'
// import Bird from 'assets/bird.svg'

export default {
  endpoints: {
    url: (process.env.TAILS_API_URL)
      ? process.env.TAILS_API_URL
      : (process.env.NODE_ENV == 'production')
      ? 'http://tails-api-dev.gpd2yfmmj5.us-west-2.elasticbeanstalk.com'
      : 'http://localhost:3001',//'http://tails-api-dev.gpd2yfmmj5.us-west-2.elasticbeanstalk.com',
    login: '/auth/signin',
    signup: '/auth/signup',
    forgot: '/auth/forgot_password',
    reset: '/auth/reset_password',
    userInfo: '/users/',
    changePass: '/users/',
    getCountry: '/locations',
    listings: '/listings',
    profile: '/users',
    bids: '/bids',
    listings_animals: '/listing_animals',
    animal_image: '/animal_images',
  },
  stripe: {
    public_key: process.env.STRIPE_PUBLIC || '',
  },
  breeds: [ 'Dog', 'Horse', 'Cow', 'Goat', 'Cat', 'Bird', 'Pig' ],
  animals: [
    {
      name: 'Cat',
      breed: 'Cat',
      url: Cat,
      breeds: [
        'Maine Coon',
        'Ragamuffin',
        'Ragdoll',
        'Persian',
        'American Shorthair',
        'Abyssinian',
        'Siamese',
        'Tonkinese',
        'Russian Blue',
        'Bengal',
        'Scottish Fold',
        'British Shorthair',
        'Siberian',
        'Exotic Shorthair',
        'Birman',
        'Himalayan',
        'Nebelung',
        'Norwegian Forest Cat',
        'American Bobtail',
        'Bombay',
        'Burmese',
        'Chartreux',
        'Chinese Li Hua',
        'Devon Rex',
        'Ocicat',
        'sphynx',
        'Other/Mixed Breed'
      ],
    },
    {
      name: 'Cow',
      breed: 'Cow',
      url: Cow,
      breeds: [
          'Angus',
          'Holstein Friesian',
          'Hereford	',
          'Shorthorn',
          'Charolais',
          'Galloway',
          'Simmental',
          'Brahman',
          'Limousin',
          'Scottish Highland',
          'Brown Swiss',
          'Texas Longhorn',
          'Brangus',
          'Jersey',
          'Ayrshire',
          'Chianina',
          'Beef Master',
          'Gelbvieh',
          'Dexter',
          'Piedmontese',
          'Watusi',
          'White Park',
          'Santa Gertrudis',
          'Braford',
          'English Longhorn',
          'Beefalo',
          'North Devon',
          'Maine-Anjou',
          'Red Poll',
          'Senepol',
          'Other/Mixed Breed'
      ],
    },
    {
      name: 'Dog',
      breed: 'Dog',
      url: Dog,
      breeds: [
          'Labrador',
          'Retrieve',
          'German Shepherd',
          'Golden Retriever',
          'Beagle',
          'Bulldog',
          'Yorkshire',
          'Terrier',
          'Boxer',
          'Poodle',
          'Rottweiler',
          'Dachshund',
          'French Bulldog',
          'German Short-Haired',
          'Siberian Husky',
          'Great Dane',
          'Doberman Pinscher',
          'Australian Shepherd',
          'Miniature Schnauzer',
          'Corgi',
          'Cavalier King',
          'Charles Spaniel',
          'Shih Tzu',
          'Pomeranian',
          'Boston Terrier',
          'Shetland Sheepdog',
          'Havanese',
          'Mastiff',
          'Brittany',
          'Chihuahua',
          'Bernese Mountain Dog',
          'Cocker Spaniel',
          'Maltese',
          'Vizlas',
          'Pug',
          'Weimaraner',
          'Cane Corso',
          'Collie',
          'Newfoundland',
          'Border Collie',
          'Basset Hound',
          'Rhodesian Ridgeback',
          'West Highland White Terrier',
          'Bullmastiff',
          'Bichon Frises',
          'Pitbull',
          'Other/Mixed'
      ]
    },
    {
      name: 'Horse',
      breed: 'Horse',
      url: Horse,
      breeds: [
          'Akhal-Teke',
          'American Paint Horse',
          'American Quarter Horse',
          'American Saddlebred',
          'Andalusian',
          'Anglo-Arabian',
          'Appaloosa',
          'Arab',
          'Azteca',
          'Belgian draft horse',
          'Canadian horse',
          'Clydesdale',
          'Dutch Warmblood',
          'Mini Horse',
          'Fjord',
          'Friesian',
          'Gypsy Vanner',
          'Haflinger',
          'Hanoverian',
          'Icelandic',
          'Irish Sport Horse',
          'Lipizzan',
          'Lusitano',
          'Morgan',
          'Mustang',
          'Oldenburg',
          'Paso Fino',
          'Standardbred',
          'Thoroughbred',
          'Shetland Pony',
          'Welsh Pony',
          'Percheron',
          'Hackney',
          'Ford',
          'Holsteiner',
          'Warmblood',
          'Tennessee Walking Horse',
          'Other/Mixed'
      ]
    },

    // {
    //     name: 'Goat',
    //     breed: 'Goat',
    //     url: Goat
    // },

    // {
    //     name: 'Bird',
    //     breed: 'Bird',
    //     url: Bird
    // },
    {
      name: 'Pig',
      breed: 'Pig',
      url: Pig,
      breeds: [
          'Berkshire',
          'Chester White',
          'Duroc',
          'Hampshire',
          'Hereford',
          'Landrace',
          'Pietrain',
          'Poland',
          'Tamworth',
          'Spot',
          'Yorkshire',
          'Minature Pig',
          'Vietnamese Potbelly',
          'Other/Mixed Breed '
      ]
    },
  ],
  countries: [
    { value: 'US', text: 'United States' },
  ],
  states: [
    { value: 'AL', text: 'Alabama' },
    { value: 'AK', text: 'Alaska' },
    { value: 'AS', text: 'American Samoa' },
    { value: 'AZ', text: 'Arizona' },
    { value: 'AR', text: 'Arkansas' },
    { value: 'CA', text: 'California' },
    { value: 'CO', text: 'Colorado' },
    { value: 'CT', text: 'Connecticut' },
    { value: 'DE', text: 'Delaware' },
    { value: 'DC', text: 'District Of Columbia' },
    { value: 'FM', text: 'Federated States Of Micronesia' },
    { value: 'FL', text: 'Florida' },
    { value: 'GA', text: 'Georgia' },
    { value: 'GU', text: 'Guam' },
    { value: 'HI', text: 'Hawaii' },
    { value: 'ID', text: 'Idaho' },
    { value: 'IL', text: 'Illinois' },
    { value: 'IN', text: 'Indiana' },
    { value: 'IA', text: 'Iowa' },
    { value: 'KS', text: 'Kansas' },
    { value: 'KY', text: 'Kentucky' },
    { value: 'LA', text: 'Louisiana' },
    { value: 'ME', text: 'Maine' },
    { value: 'MH', text: 'Marshall Islands' },
    { value: 'MD', text: 'Maryland' },
    { value: 'MA', text: 'Massachusetts' },
    { value: 'MI', text: 'Michigan' },
    { value: 'MN', text: 'Minnesota' },
    { value: 'MS', text: 'Mississippi' },
    { value: 'MO', text: 'Missouri' },
    { value: 'MT', text: 'Montana' },
    { value: 'NE', text: 'Nebraska' },
    { value: 'NV', text: 'Nevada' },
    { value: 'NH', text: 'New Hampshire' },
    { value: 'NJ', text: 'New Jersey' },
    { value: 'NM', text: 'New Mexico' },
    { value: 'NY', text: 'New York' },
    { value: 'NC', text: 'North Carolina' },
    { value: 'ND', text: 'North Dakota' },
    { value: 'MP', text: 'Northern Mariana Islands' },
    { value: 'OH', text: 'Ohio' },
    { value: 'OK', text: 'Oklahoma' },
    { value: 'OR', text: 'Oregon' },
    { value: 'PW', text: 'Palau' },
    { value: 'PA', text: 'Pennsylvania' },
    { value: 'PR', text: 'Puerto Rico' },
    { value: 'RI', text: 'Rhode Island' },
    { value: 'SC', text: 'South Carolina' },
    { value: 'SD', text: 'South Dakota' },
    { value: 'TN', text: 'Tennessee' },
    { value: 'TX', text: 'Texas' },
    { value: 'UT', text: 'Utah' },
    { value: 'VT', text: 'Vermont' },
    { value: 'VI', text: 'Virgin Islands' },
    { value: 'VA', text: 'Virginia' },
    { value: 'WA', text: 'Washington' },
    { value: 'WV', text: 'West Virginia' },
    { value: 'WI', text: 'Wisconsin' },
    { value: 'WY', text: 'Wyoming' },
  ],
}
